import type { Service } from '../types';

export const perplexityProService: Service = {
  name: 'Perplexity Pro',
  keyData: `# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
.perplexity.ai	TRUE	/	FALSE	1768278984	_gcl_au	1.1.734870517.1760502984
www.perplexity.ai	FALSE	/	FALSE	1761961999	pplx.session-id	c36742b7-4334-4f52-947b-2b26c6694176
www.perplexity.ai	FALSE	/	FALSE	1792892290	sidebar-upgrade-badge	10
www.perplexity.ai	FALSE	/	FALSE	1796435592	pplx.metadata	{%22qc%22:16%2C%22qcu%22:0%2C%22qcm%22:0%2C%22qcc%22:0%2C%22qcco%22:0%2C%22qccol%22:0%2C%22qcdr%22:0%2C%22qcs%22:0%2C%22qcd%22:0%2C%22hli%22:true%2C%22hcga%22:false%2C%22hcds%22:false%2C%22hso%22:false%2C%22hfo%22:false%2C%22hsco%22:false%2C%22hfco%22:false%2C%22hsma%22:false%2C%22hdc%22:false%2C%22fqa%22:1760503039167%2C%22lqa%22:1761275033611}
.perplexity.ai	TRUE	/	TRUE	1769051036	_rdt_uuid	1760502997665.1cd36616-6923-41f8-97e0-3f527f5fd478
#HttpOnly_.perplexity.ai	TRUE	/	TRUE	1761877391	__cf_bm	awJ7NktPvWQwTpCkaEi.b4GhPwTWj4Nu2E9g0Lw6jBk-1761875591-1.0.1.1-fGXuZRD38KMLmK5b7HGbFmtGZCaNiXRG9dS.6rSJW6zMMjAWA6Fw6vIQskgCVNmFDuHZXOgh9Dwyc5uYKMd2kixXMjKCxtPRh1fFIo8sma8
www.perplexity.ai	FALSE	/	TRUE	1793411592	_dd_s	aid=ac5a49c0-4bca-42d4-a2f7-7103ee2cd7be&rum=2&id=06ddef08-f92f-4ecb-892e-3acbcec25720&created=1761875592242&expire=1761876492263&logs=0
.perplexity.ai	TRUE	/	TRUE	1792038997	__ps_lu	https://www.perplexity.ai/
www.perplexity.ai	FALSE	/	FALSE	1792038981	pplx.visitor-id	e006041d-bb6e-435a-b884-ad423628cb02
#HttpOnly_www.perplexity.ai	FALSE	/	TRUE	1761961999	next-auth.csrf-token	d71f13ec8168282d8b31274ed47976543695bc7c1a0e57c2c15eb36aa15ad76c%7C17ef76119f9d95981bc65b03ee55633da17d23d24162ab2f20d627f0557a4a73
.perplexity.ai	TRUE	/	TRUE	1792038997	__ps_r	_
www.perplexity.ai	FALSE	/	TRUE	1762094324	AWSALBCORS	hlzxjWDnh9nVPofaO53R2OoTckM9rHw5U01augvEQLS0VDp5/NrJ0bengz/fhL1lTqIlyfpSyB7qj+lwS0CnKNSss+rXpxrtMf6w+bzWhlh99T7jID8wqFAqfVavsdeFEVNlwm90oU+zmkSwK6KTHB1KCfGsX6h0O76HEFXHMidOipHm2Q/SndvoC927dg==
www.perplexity.ai	FALSE	/	FALSE	1796435593	sidebarHiddenHubs	[]
#HttpOnly_www.perplexity.ai	FALSE	/	TRUE	1761895838	__cflb	02DiuDyvFMmK5p9jVbVnMNSKYZhUL9aGkmo9DFMnoH1j2
.perplexity.ai	TRUE	/	TRUE	1792038997	__ps_fva	1760502997399
#HttpOnly_www.perplexity.ai	FALSE	/	TRUE	1764467592	__Secure-next-auth.session-token	eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..HtdzdYpxqeN7Cszs.hG5snRmxajAki3-jmoJyd4XvLY3q_xker8CpcUcUiHwTaz7ZzgJc3b5EU0XWdUIN5Uf6Uvxtp_2En7eYW0zuuGT5QUFT3--w7p8cxiteMH84WWom3xf8H3zUdBnwkdNoKZKZBMpk8U-fK6cBo9LL0HeWPbcX1QY_at5NRC0JlzTUUbbWuD-9wpUP4XSKmENx3BaFwfyNOhWGh4sFx0OlqjIFSu_p6uxSZn49FOCJEHtSLL1wRJOViuB1OCiDB2SL0A.l-BVizPh__TTn1vDhb7Q_g
.www.perplexity.ai	TRUE	/	TRUE	1792039042	__stripe_mid	2fce0be0-ec90-4339-a7be-dbff0f2e7533240971
.perplexity.ai	TRUE	/	FALSE	1769095408	_fbp	fb.1.1760502997793.89031110641460050
www.perplexity.ai	FALSE	/	FALSE	1762094324	AWSALB	hlzxjWDnh9nVPofaO53R2OoTckM9rHw5U01augvEQLS0VDp5/NrJ0bengz/fhL1lTqIlyfpSyB7qj+lwS0CnKNSss+rXpxrtMf6w+bzWhlh99T7jID8wqFAqfVavsdeFEVNlwm90oU+zmkSwK6KTHB1KCfGsX6h0O76HEFXHMidOipHm2Q/SndvoC927dg==
www.perplexity.ai	FALSE	/	FALSE	1776054997	g_state	{"i_l":0,"i_ll":1760502997897,"i_b":"2YWcTH9pg7bht+iMurgkfo4xBh/R2NeTuARzFgNcyG8"}
www.perplexity.ai	FALSE	/	FALSE	1792645490	gov-badge	3
www.perplexity.ai	FALSE	/	TRUE	1761961999	next-auth.callback-url	https%3A%2F%2Fwww.perplexity.ai
www.perplexity.ai	FALSE	/	FALSE	1795692515	pplx.search-models-v4	{%22search%22:%22gemini2flash%22}`,
  status: 'available',
  gradient: 'from-cyan-400 to-teal-500',
  glowColor: '34, 211, 238',
  url: 'https://www.perplexity.ai/',
};